## 📚 Introduction to Python's NumPy library for Linear Algebra

Linear algebra is the mathematical language behind data science, computer graphics, machine learning, scientific computing, and more. To work effectively with vectors and matrices on a computer, we need a tool that is fast, easy to use, mathematically reliable and able to scale to large datasets.

NumPy implements the core operations of linear algebra including matrix multiplication, determinants, computing eigenvalues and eigenvectors and singular value decomposition.Numpy is *gateway library* for scientific computing in Python.

***

## 🔢 Understanding NumPy Arrays: Dimensions, Shape, and Size

NumPy’s main building block is the **ndarray** — short for **N‑dimensional array**.  
You can think of it as a container that holds numbers in a structured way, like:

*   a list (1D),
*   a table (2D),
*   or even more complex grids (3D, 4D, …).

A NumPy array is a collection of numbers arranged in a fixed shape.

Example:

```python
import numpy as np

a = np.array([1, 2, 3])  # 1D array
b = np.array([[1, 2, 3],
              [4, 5, 6]])  # 2D array
```



#### Create an **2x3** matrix A below using np.array

$$
A =
\begin{bmatrix}
-1 & 0 & 5 \\
7 & -2 & 4
\end{bmatrix}
$$

Call your matrix a. Print a. Use print(a).

In [9]:
b = np.array([[1, 2, 3],
              [4, 5, 6]])  # 2D array


## 📐 Shape (`shape`)

The shape tells you **how many elements** are along each dimension.

For a 2D array:

    shape = (number_of_rows, number_of_columns)

Example:

```python

a = np.array([1, 2, 3])  # 1D array
b = np.array([[1, 2, 3],
              [4, 5, 6]])  # 2D array
              
print(a.shape)   # (3,)
print(b.shape)   # (2, 3)
```

Interpretation:

*   `a` has 3 elements in one dimension
*   `b` has 2 rows and 3 columns




#### Print out the shape of your matrix a. 

#### Create the two **2x3** matrix A and B below and add them. Store the result in variable c. Note you already created the variable a above so you do not need to recreate it.

$$
A =
\begin{bmatrix}
-1 & 0 & 5 \\
7 & -2 & 4
\end{bmatrix}
$$

$$
B =
\begin{bmatrix}
2 & 3 & 9 \\
4 & 6 & -1
\end{bmatrix}
$$



Compute the scalar multiplication $-0.5A$. Use the * operator. Note if you do not use print(), running the cell will output the value of the expression. 

#### Create the **3x2** C below so that matrix multiplication AC is compatible. Use the @ operator. 
$$
C =
\begin{bmatrix}
2 & -1 \\
0 & 3 \\
3 & 1 
\end{bmatrix}
$$


In [14]:
c = np.array([[2, -1],
              [0,3],
              [3,1]])

In [16]:
b@c

array([[11,  8],
       [26, 17]])

In [17]:
np.dot(b,c)

array([[11,  8],
       [26, 17]])

## NumPy Slicing

When you work with NumPy, you often need to extract **parts** of an array rather than the whole thing. This is called **slicing**, and it works a lot like cutting out a section of a list or table.

Think of a NumPy array like a grid of numbers — slicing lets you say:  
➡️ “Give me rows from here to here”  
➡️ “Give me columns from here to here”  
➡️ “Give me every second value”  
…and so on.

***

### 🔹 Basic Slicing: `start : stop`

The simplest form is:

    array[start : stop]

*   `start` = where to begin (included)
*   `stop` = where to end (not included)

Example:

```python
import numpy as np

a = np.array([10, 20, 30, 40, 50])
a[1:4]
```

This gives:

    array([20, 30, 40])

Because it starts at index 1 and stops *before* index 4.

#### Use the numpy array a below and use slicing to extract the first three numbers.


In [ ]:
a = np.array([10, 20, 30, 40, 50])


### 🔹 Slicing 2D Arrays (Rows and Columns)

Think of a 2D array like a table:

*   The first number selects **rows**
*   The second number selects **columns**

Format:

    array[row_start:row_stop , col_start:col_stop]

Example:

```python
b = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

b[0:2, 1:3]
```

This selects:

*   Rows 0 and 1
*   Columns 1 and 2

Result:

    array([
        [2, 3],
        [5, 6]
    ])

#### Use the array b below and use slicing to extract the first two rows and the last two columns

In [18]:
b = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

### 🔹 Shortcut: Leaving Start or Stop Empty

You can leave out `start` or `stop`:

*   `a[:3]` → from the beginning to index 2
*   `a[2:]` → from index 2 to the end
*   `a[:]` → the whole array

Example:

```python
b[:, 1]
```

Means:

*   all rows
*   column 1 only

Result:

    array([2, 5, 8])

***

### ⭐ Quick Summary

| Pattern              | Meaning               |
| -------------------- | --------------------- |
| `a[start:stop]`      | Slice 1D array        |
| `a[:, :]`            | All rows, all columns |
| `a[x, :]`            | Row `x`, all columns  |
| `a[:, y]`            | All rows, column `y`  |

#### Use the b array below and use slicing as before to extract the first two rows and the last two columns of b but leave the start and stop empty.



In [ ]:
b = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])



## 🔍 Eigenvalues andd Eigenvectors using the `np.linalg.eig` Function

NumPy’s **`np.linalg.eig`** function computes the **eigenvalues** and **eigenvectors** of a square matrix $A$. It solves the equation:

$$
A v = \lambda v
$$

Here's how to use it:
```python
eigvals, eigvecs = np.linalg.eig(A)
```

*   **`eigvals`** → a 1D array containing the eigenvalues
*   **`eigvecs`** → a 2D array where each **column** is an eigenvector
    *   `eigvecs[:, i]` corresponds to `eigvals[i]` (Note the use of slicing)

*   Eigenvectors from NumPy are **normalized** (length 1).


#### Calculate the eigenvalues and eigenvectors of A below. Print out the results. 

In [19]:
A = np.array([[ 1,  3,  3],
              [-3, -5, -3],
              [ 3,  3,  1]], dtype=float)

eigvals, eigvecs = np.linalg.eig(A)


Eigenvalues:
 [ 1. -2. -2.]

Eigenvectors (columns):
 [[-0.57735027 -0.30650601 -0.6284002 ]
 [ 0.57735027  0.80864644 -0.13728067]
 [-0.57735027 -0.50214043  0.76568088]]


#### Extract the first eigenvalue i = 0 and corresponding eigenvector. Use slicing. Then manually check by printing that
$$A v_i=\lambda v_i$$

In [31]:
i = 0
lam_i = 
v_i = 



[-0.57735027  0.57735027 -0.57735027] [-0.57735027  0.57735027 -0.57735027]
[ 0.61301202 -1.61729287  1.00428085] [ 0.61301202 -1.61729287  1.00428085]
[ 1.2568004   0.27456135 -1.53136175] [ 1.2568004   0.27456135 -1.53136175]


#### Check all three eigenvalues and eigenvectors by using a for loop.

In [ ]:
for i in range(3):
    i = 0
    lam_i = 
    v_i = 
    